version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m unittest discover -s online_election
artifacts:
  files:
    - '**/*'
  base-directory: online_election
