# You must set this file into .elasticbeanstalk direcotry like this;
# .elasticbeanstalk/config.yml

branch-defaults:
  default:
    environment: e-voting-env
environment-defaults:
  e-voting-env
    branch: null
    repository: null
global:
  application_name: e-voting
  default_ec2_keyname: null
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application